apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fail2
spec:
  args:
  - name: msg
  metrics:
  - name: fail2
    count: 1
    interval: 0s
    failureLimit: 0
    provider:
      job:
        spec:
          # ttlSecondsAfterFinished: 2
          backoffLimit: 0 # run once
          template:
            spec:
              containers:
              - name: failure #{{args.msg}}
                image: yptosammy/newmanneke:1 #alpine/curl
                # command: [sh, -c]                
                # args: [echo "hi $test" && sleep 5 && curl http://rollout-ngnix-preview] #
                # env:
                # - name: test
                #   value: "{{args.msg}}"
              restartPolicy: Never