apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: fridayvnet-9091c216942306671fb5474bd43ded9fbdda0bbd
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: UK South
    resourceGroupName: Kubernetes_Cluster_RG
