apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  naam: hithere-3b09bca885f44c81afbac5d28960cb97d47f5239
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: East US
    resourceGroupName: Kubernetes_Cluster_RG
