apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: hello-provider-github
spec:
  forProvider:
    visibility: public
    name: bonjour-everybody
  providerConfigRef:
    name: default