apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: terraform-azure-sammy
spec:
  forProvider:
    source: Inline
    module: |
      resource "azuredevops_project" "project" {
        name        = "ProjectName"
        visibility         = "private"
        version_control    = "Git"
        work_item_template = "Agile"
      }

      resource "azuredevops_git_repository" "code_repo" {
        project_id     = azuredevops_project.project.id
        name           = "code"
        default_branch = "refs/heads/master"
        initialization {
          init_type = "Clean"
        }
      }
      resource "azuredevops_git_repository" "infra_repo" {
        project_id     = azuredevops_project.project.id
        name           = "infra"
        default_branch = "refs/heads/master"
        initialization {
          init_type = "Clean"
        }
      }
  providerConfigRef:
    name: azure-terraform


# resource "kubernetes_namespace" "test" {
  #   metadata {
  #     name = "test"

  #     labels = {
  #       app = "nginx"
  #     }
  #   }
  # }